[package]
name = "dupefinder"
version = "0.1.0"
edition = "2021"
description="A duplicate file finding utility library that supports directory recursion, multiple directories, and specific file duplicate searching."

[dependencies]
log = "0.4.20"
sha2 = "0.10.8"
